Repository schubergphilis/terraform-aws-mcaf-route53-resolver, pull requests merged in 2025-08, with the labels that each got.

#5 breaking: Resolver rule
  README.md
  UPGRADING.md
  examples/basic/main.tf
  main.tf
  modules/resolver-logging/README.md
  modules/resolver-logging/main.tf
  modules/resolver-logging/terraform.tf
  modules/resolver-logging/variables.tf
  modules/resolver-rules/README.md
  modules/resolver-rules/main.tf
  modules/resolver-rules/outputs.tf
  modules/resolver-rules/terraform.tf
  modules/resolver-rules/variables.tf
  variables.tf
Labels: breaking

#6 chore: update upgrading.md
  CHANGELOG.md
Labels: chore

#7 enhancement: add feature for resolver rule association
  examples/basic/main.tf
  modules/resolver-rules/README.md
  modules/resolver-rules/main.tf
  modules/resolver-rules/variables.tf
Labels: feature
